### ISSUE TITLE
Desktop strategy not working - Quota exceeded

### ISSUE THREAD

**Issue by vmincev** [GoogleChromeLabs/psi#123]
```
psi https://addyosmani.com --strategy=desktop

Error: Quota exceeded for quota metric 'Queries' and limit 'Queries per minute' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.
    at Gaxios.<anonymous> (/usr/local/lib/node_modules/psi/node_modules/gaxios/build/src/gaxios.js:73:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/psi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Mobile strategy still works properly.

**Comment by joshunger** [comment]
Still exists

```
Error: Quota exceeded for quota metric 'Queries' and limit 'Queries per minute' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.
    at Gaxios._request (/Users/junger/.config/yarn/global/node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
