### ISSUE TITLE
Threshold of 70 not met with score of 53

### ISSUE THREAD

**Issue by peterpme** [GoogleChromeLabs/psi#31]
Is the website I tested that bad? 

```
Error: Threshold of 70 not met with score of 53
    at Object.exports.process (/Users/peter/.nvm/v0.10.26/lib/node_modules/psi/output.js:72:13)
    at /Users/peter/.nvm/v0.10.26/lib/node_modules/psi/index.js:26:12
    at Request._callback (/Users/peter/.nvm/v0.10.26/lib/node_modules/psi/node_modules/gpagespeed/index.js:24:12)
    at Request.self.callback (/Users/peter/.nvm/v0.10.26/lib/node_modules/psi/node_modules/gpagespeed/node_modules/request/request.js:122:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/peter/.nvm/v0.10.26/lib/node_modules/psi/node_modules/gpagespeed/node_modules/request/request.js:1019:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/peter/.nvm/v0.10.26/lib/node_modules/psi/node_modules/gpagespeed/node_modules/request/request.js:970:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

**Comment by danimalweb** [comment]
Is it possible to get the error passed to the callback?
